language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.502
script:
  - dotnet restore
  - dotnet build
  - dotnet publish -c Release
before_deploy:
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking
      no" >> ~/.ssh/config
    - chmod 600 deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -e "ssh -i deploy_rsa -p $server_port" $TRAVIS_BUILD_DIR/backendHackathone/bin/Release/netcoreapp2.1/publish/
        $server_user@$server_ip:/home/marchenkors/www/testapp/publish
    on:
        branch: master 
before_install:
- openssl aes-256-cbc -K $encrypted_3656ade6b6b0_key -iv $encrypted_3656ade6b6b0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
after_deploy:
  - ssh -i deploy_rsa -p $server_port $server_user@$server_ip bash -c "echo $secret | sudo -S systemctl restart kestrel-test.service"